title: Personal website of Hui Wu 
email: wuhu@us.ibm.com
greeting: Welcome to Hui Wu's website 
description: > # this means to ignore newlines until another tag
    Research Scientist, IBM Research AI 
twitter:  huiwu_
linkedin: hui-wu-90381966
google scholar: https://scholar.google.com/citations?user=1qByqaUAAAAJ&hl=en&oi=ao
#favicon: favicon.png

# Build settings
paginate: 3
baseurl: "" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "http://spacew.github.io" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
gems: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

# cover images are expected to be 900px by 240px, or at least 15:4 aspect ratio
# thumbnails look best with 3:1 or 5:2 ratios in this layout.
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Hui Wu"
            cover: "/media/yorktown.png"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Hui Wu"
            cover: "/media/yorktown.png"
            layout: "default"
